"""variacao_busca

Revision ID: 16acce0b732e
Revises: dfa50837db60
Create Date: 2026-08-20 14:14:33.461632
"""
from alembic import op
import sqlalchemy as sa


revision = '16acce0b732e'
down_revision = 'dfa50837db60'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('variacao_busca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('variacao', sa.String(length=500), nullable=False),
    sa.Column('vezes_encontrada', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('categoria', 'variacao', name='uq_categoria_variacao')
    )
    op.create_index(op.f('ix_variacao_busca_categoria'), 'variacao_busca', ['categoria'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_variacao_busca_categoria'), table_name='variacao_busca')
    op.drop_table('variacao_busca')
    # ### end Alembic commands ###
