"""schema inicial

Revision ID: d48eff59f5e3
Revises: 
Create Date: 2026-08-18 18:48:21.628208
"""
from alembic import op
import sqlalchemy as sa


revision = 'd48eff59f5e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('pontos_venda', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('historico_preco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_normalizado', sa.String(length=255), nullable=False),
    sa.Column('local', sa.String(length=255), nullable=False),
    sa.Column('preco_centavos', sa.Integer(), nullable=False),
    sa.Column('variacao_pct', sa.Float(), nullable=True),
    sa.Column('dias_desde_ultima', sa.Integer(), nullable=True),
    sa.Column('coletado_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_hist_produto_local', 'historico_preco', ['produto_normalizado', 'local', sa.literal_column('coletado_em DESC')], unique=False)
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('perms', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('justificativa', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('lista_compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('escopo', sa.String(length=20), nullable=False),
    sa.Column('localizacao', sa.String(length=120), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resultado_busca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lista_id', sa.Integer(), nullable=False),
    sa.Column('produto', sa.String(length=255), nullable=False),
    sa.Column('marca', sa.String(length=120), nullable=True),
    sa.Column('preco_centavos', sa.Integer(), nullable=True),
    sa.Column('moeda', sa.String(length=8), nullable=False),
    sa.Column('local', sa.String(length=255), nullable=False),
    sa.Column('link', sa.Text(), nullable=False),
    sa.Column('fonte', sa.String(length=60), nullable=False),
    sa.Column('disponibilidade', sa.String(length=20), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('coletado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lista_id'], ['lista_compra.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_resultado_lista', 'resultado_busca', ['lista_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_resultado_lista', table_name='resultado_busca')
    op.drop_table('resultado_busca')
    op.drop_table('lista_compra')
    op.drop_table('usuario')
    op.drop_table('role')
    op.drop_index('idx_hist_produto_local', table_name='historico_preco')
    op.drop_table('historico_preco')
    op.drop_table('categoria')
    # ### end Alembic commands ###
