"""identidade: senha e job_busca

Revision ID: dfa50837db60
Revises: d48eff59f5e3
Create Date: 2026-08-19 08:17:50.469089
"""
from alembic import op
import sqlalchemy as sa


revision = 'dfa50837db60'
down_revision = 'd48eff59f5e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_busca',
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.add_column('usuario', sa.Column('senha_hash', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'senha_hash')
    op.drop_table('job_busca')
    # ### end Alembic commands ###
